services:
  server1:
    build:
      context: ./server1
      dockerfile: Dockerfile # Указываем Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      NODE_ENV: production

  server2:
    build:
      context: ./server2
      dockerfile: Dockerfile # Указываем Dockerfile
    ports:
      - "8089:8089"
    networks:
      - app-network
    environment:
      NODE_ENV: production

networks:
  app-network:
    driver: bridge